workspace:
  base: /go
  path: src/github.com/craig0213/droneDemo

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  testing:
    image: golang:1.14.0
    commands:
      - go test -v .
      - go vet

    